// Decompiled with JetBrains decompiler
// Type: Eco.Gameplay.Settlements.Components.SettlementFoundationComponent
// Assembly: Eco.Gameplay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E91D36E0-DE51-4020-BCDC-BDFD4EB61D56
// Assembly location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.Gameplay.dll
// XML documentation location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.Gameplay.xml

using Eco.Core.Controller;
using Eco.Core.PropertyHandling;
using Eco.Core.Utils;
using Eco.Gameplay.Civics.Elections;
using Eco.Gameplay.InfluenceObjects;
using Eco.Gameplay.Items;
using Eco.Gameplay.Objects;
using Eco.Gameplay.Placement;
using Eco.Gameplay.Players;
using Eco.Shared.Items;
using Eco.Shared.Localization;
using Eco.Shared.Networking;
using Eco.Shared.Serialization;
using Eco.Shared.Utils;
using System;

#nullable disable
namespace Eco.Gameplay.Settlements.Components;

[LocDescription("Allows the initial founding of the settlement once requirements are met.")]
[Serialized]
[Priority(100)]
[CreateComponentTabLoc(null, false)]
[HasIcon(null)]
public sealed class SettlementFoundationComponent : 
  WorldObjectComponent,
  IPostAddListenerComponent,
  IClaimStakeComponent,
  IPickupConfirmationComponent,
  IHasBaseInfluence,
  IInventoryWorldObjectComponent,
  IPermanentDestroyHandler,
  IHostsObjects
{
  public Action FoundedSettlementInited;
  public static ThreadSafeAction<Settlement> SettlementPictureChangeEvent;
  public static ThreadSafeAction<Settlement> SettlementFoundedEvent;

  [SyncToView(null, true)]
  public override LocString ComponentTabName { get; }

  [SyncToView(null, true)]
  [Autogen]
  [UITypeName("StringPlaque")]
  public LocString TitlePlate { get; set; }

  [SyncToView(null, true)]
  public Settlement Settlement { get; }

  public SettlementType SettlementType { get; }

  Settlement IClaimStakeComponent.OwningSettlement { get; }

  [SyncToView(null, true)]
  public bool NotFounded { get; }

  [Notify]
  [DependsOnSubMember("SettlementReqs", "AllPassed")]
  public override bool Enabled { get; }

  [SyncToView(null, true)]
  public bool AdminMode(Player player);

  [Eco.Shared.Networking.Eco(true)]
  [GuestEditable]
  [VisibilityParam("AdminMode")]
  [LocDisplayName("Admin Mode: Settlement Must Have Children")]
  [LocDescription("When set, the settlement will be unplaced when it lacks children settlements (or when it lacks citizens, if it cannot have children settlements).")]
  public bool MustHaveChildren { get; set; }

  [Eco.Shared.Networking.Eco(true)]
  [LocDescription("The founding of a Settlement will create an influence area that can be observed on the map. The chosen color will signify the extent of influence generated by this Settlement.")]
  public Color InfluenceColor { get; set; }

  [Eco.Shared.Networking.Eco(true)]
  [UITypeName("StringInput")]
  [VisibilityParam("NotFounded")]
  [Range(3f, 50f)]
  public string SettlementNameUponFounding { get; set; }

  [Eco.Shared.Networking.Eco(false)]
  [UITypeName("TextInput")]
  [LocDescription("Citizens entering the world will be able to view this on map as they select their initial spawn point. Write a brief description of your town, how you want to run it, and why it would be a good place to join (can only be edited by Citizens with Diplomatic Privilege in this settlement).")]
  [EnabledParam("HasDiplomaticPrivilege")]
  [EcoTextLimit(EcoTextLimitAttribute.TextRangeStyle.LongText)]
  public string AdvertisementToNewPeopleEnteringWorld { get; set; }

  [SyncToView(null, true)]
  [DependsOnSubMember("Settlement", "Founded")]
  public bool ShowPicture { get; }

  [SyncToView(null, true)]
  [Autogen]
  [UITypeName("GeneralHeader")]
  [VisibilityParam("ShowPicture")]
  public LocString Title { get; }

  [Eco.Shared.Networking.Eco(true)]
  [UITypeName("PictureWithPreview")]
  [VisibilityParam("ShowPicture")]
  public LimitedInventory PictureSlot { get; set; }

  [SyncToView(null, true)]
  [DependsOnSubMember("Settlement", "Founded")]
  public bool ShowFoundButton { get; }

  [SyncToView(null, true)]
  public bool CanFound { get; }

  [SyncToView(null, true)]
  public bool HasDiplomaticPrivilege(User user);

  [SyncToView(null, true)]
  public string FoundSettlementTitle();

  public override void Initialize();

  void IHostsObjects.UpdateHostedStatus();

  [Autogen]
  [RPC]
  [UITypeName("BigButton")]
  [DynamicTitle("FoundSettlementTitle")]
  [EnabledParam("CanFound")]
  [VisibilityParam("ShowFoundButton")]
  public void FoundSettlement(User user);

  /// <summary>Get a Settlement picture description.</summary>
  public LocString FoundationPictureDescription();

  /// <summary>Helper that forces founding of the settlement. Called directly when founding via ratification.
  /// Takes an optional param for an election that founded it, stored for posterity.</summary>
  public void DoFounding(Election foundingElection = null);

  void IClaimStakeComponent.DeedChanged();

  Result IPickupConfirmationComponent.CanPickup();

  public override void Destroy();

  public void PostAdd();

  float IHasBaseInfluence.BaseInfluence { get; }

  Inventory IInventoryWorldObjectComponent.Inventory { get; }
}
