// Decompiled with JetBrains decompiler
// Type: Eco.WebServer.Web.Controllers.LogController
// Assembly: Eco.WebServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 928A4994-7F56-454E-B344-AF537A2B649B
// Assembly location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.WebServer.dll
// XML documentation location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.WebServer.xml

using Eco.Core.Utils.Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

#nullable enable
namespace Eco.WebServer.Web.Controllers;

/// <summary>MVC <seealso cref="T:Microsoft.AspNetCore.Mvc.Controller" /> instance that provides API access to the logs generated by the Eco game server.</summary>
[Authorize(Policy = "RequireAdmin")]
[Route("api/v1/logs")]
public class LogController : Controller
{
  public LogController(LogFileManager logManager);

  /// <summary>Retrieves a list of all log files on the server.</summary>
  [HttpGet("")]
  public List<string> GetAllLogs();

  /// <summary>Retrieves a list of all log files in the requested category subfolder if it exists.</summary>
  /// <param name="category">Category log subfolder to search.</param>
  [HttpGet("{category}")]
  public List<string> GetCategoryLogs(string category);

  /// <summary>Streams a log file over HTTP/HTTPS to a client.</summary>
  /// <param name="filepath">Filepath of the log file to stream.</param>
  [HttpGet("get")]
  public PhysicalFileResult GetLogFile(string filepath);
}
