// Decompiled with JetBrains decompiler
// Type: Eco.Gameplay.Systems.NewTooltip.TooltipPart
// Assembly: Eco.Gameplay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E91D36E0-DE51-4020-BCDC-BDFD4EB61D56
// Assembly location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.Gameplay.dll
// XML documentation location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.Gameplay.xml

using Eco.Core.Controller;
using Eco.Gameplay.Players;
using Eco.Shared.Items;
using Eco.Shared.Localization;
using System;
using System.Collections.Generic;
using System.Reflection;

#nullable disable
namespace Eco.Gameplay.Systems.NewTooltip;

/// <summary>
/// Server side implmentation of the tooltip part, built from members with NewTooltip attributes on them.
/// It stores all the relevant data about the part and shares it with the client.
/// It also contains the actual cached data for each tooltip part, which is used to get the text
/// when a user queries a tooltip.
/// </summary>
/// <remarks>See 'Tooltip.md' for more info.</remarks>
public class TooltipPart : TooltipPartBase
{
  public static void InitializeCache(int size);

  /// <summary>Clear the cache of all tooltip parts.</summary>
  public static void ClearAllCache();

  [SyncToView(null, true)]
  public override bool IsTitle { get; }

  [SyncToView(null, true)]
  public override bool IsImage { get; }

  [SyncToView(null, true)]
  public string CustomEcopediaPage { get; }

  /// <summary>The attribute from which this part was created.</summary>
  public NewTooltipAttribute Attribute { get; set; }

  [SyncToView(null, true)]
  public TTCat Categories { get; }

  [SyncToView(null, true)]
  public float Priority { get; }

  /// <summary>
  /// Create the tooltip part for the given member, passing in the attribute (to avoid a requery) and the root type (which may be different
  /// than the member declared type, in the case of TooltipLibraries that specify an override type).
  /// </summary>
  public TooltipPart(MemberInfo member, NewTooltipAttribute attr, Type rootType);

  /// <summary>Takes delegate generated by base class and after adding necessary casts sets it as tooltip generator.</summary>
  protected override void SetGenerator(TooltipPartBase.GetValueFromMember generator);

  /// <summary>Main cache querying function. Get thes type + obj + origin + user and returns the cache for that combo, or builds it if it doesnt exist</summary>
  public LocString GetText(Type type, IController controller, TooltipOrigin origin, User user);

  public override LocString GenerateDebugText(
    IController controller,
    TooltipOrigin origin,
    User user);

  public override List<KeyValuePair<(int ControllerID, TooltipOrigin Origin), LocString>> GetInternalCache();

  public override string ToString();

  /// <summary>Clear cache for object with given id.</summary>
  public override void ClearCache(int id);

  private delegate LocString GenerateTooltipPartText(
    Type type,
    IController controller,
    User user,
    TooltipOrigin origin);
}
