// Decompiled with JetBrains decompiler
// Type: Eco.Gameplay.Systems.NewTooltip.TooltipChildrenPart
// Assembly: Eco.Gameplay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E91D36E0-DE51-4020-BCDC-BDFD4EB61D56
// Assembly location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.Gameplay.dll
// XML documentation location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.Gameplay.xml

using Eco.Core.Controller;
using Eco.Gameplay.Players;
using Eco.Shared.Items;
using Eco.Shared.Localization;
using System;
using System.Collections.Generic;
using System.Reflection;

#nullable disable
namespace Eco.Gameplay.Systems.NewTooltip;

[ForceCreateView]
public class TooltipChildrenPart : TooltipPartBase
{
  public static void InitializeCache(int size);

  /// <summary>Clear the cache of all tooltip children parts.</summary>
  public static void ClearAllCache();

  /// <summary>The attribute from which this part was created.</summary>
  public NewTooltipChildrenAttribute Attribute { get; set; }

  [SyncToView(null, true)]
  public override bool IsTitle { get; }

  [SyncToView(null, true)]
  public override bool IsImage { get; }

  [SyncToView(null, true)]
  public TTCat ExcludeCategories { get; }

  public TooltipChildrenPart(
    MemberInfo member,
    NewTooltipAttributeBase attr,
    Type rootType,
    bool allowNonControllerType = false);

  /// <summary>Returns all child controllers.</summary>
  public IEnumerable<IController> GetChildren(
    Type type,
    IController controller,
    User user,
    TooltipOrigin origin);

  public override string ToString();

  /// <summary>Clear cache for object with given id.</summary>
  public override void ClearCache(int id);

  public override LocString GenerateDebugText(
    IController controller,
    TooltipOrigin origin,
    User user);

  public override List<KeyValuePair<(int ControllerID, TooltipOrigin Origin), LocString>> GetInternalCache();

  /// <summary>Takes delegate generated by base class and after adding necessary casts sets it as child controller getter.</summary>
  protected override void SetGenerator(TooltipPartBase.GetValueFromMember generator);

  private delegate IEnumerable<IController> GetChildControllers(
    Type type,
    IController controller,
    User user,
    TooltipOrigin origin);
}
