// Decompiled with JetBrains decompiler
// Type: Eco.Gameplay.GameActions.DinnerPartyEnded
// Assembly: Eco.Gameplay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E91D36E0-DE51-4020-BCDC-BDFD4EB61D56
// Assembly location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.Gameplay.dll
// XML documentation location: C:\Users\orfla\OneDrive\Documents\ecoserveur\EcoModKit_v0.14.0.3-beta\ReferenceAssemblies\Eco.Gameplay.xml

using Eco.Gameplay.Civics;
using Eco.Shared.Localization;

#nullable disable
namespace Eco.Gameplay.GameActions;

[Eco.Shared.Networking.Eco(true, Serialized = false)]
[LocCategory("Dinner Party")]
[LocDescription("A dinner party has finished.")]
[ExtendedDescriptionLocStr("Triggers laws on settlements influencing the deed.")]
[CannotBePrevented]
public class DinnerPartyEnded : DinnerPartyAction
{
  [Eco.Shared.Networking.Eco(true)]
  [LocDescription("Number of guests who attended.")]
  public int GuestCount { get; set; }

  [Eco.Shared.Networking.Eco(true)]
  [LocDescription("Total culture generated by the dinner party.")]
  public float CultureTotal { get; set; }

  [Eco.Shared.Networking.Eco(true)]
  [LocDescription("Number of different settlements whose members attended.")]
  public int SettlementCount { get; set; }

  [Eco.Shared.Networking.Eco(true)]
  [LocDescription("Total number of dishes eaten across all guests.")]
  public int MealsCount { get; set; }
}
